site_name: Curso de Splunk
site_description: Documentación y prácticas del curso de Splunk
site_author: Guillem Hernandez Sola
site_url: https://agile611.github.io/startusingsplunk/

repo_name: agile611/startusingsplunk
repo_url: https://github.com/agile611/startusingsplunk

theme:
  name: material
  language: es
  logo: https://www.agile611.com/wp-content/uploads/2020/09/cropped-logo-header.png
  font:
    text: Nunito
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Curso de Splunk:
      - Introducción: index.md
      - "1.1 Infraestructura como código": 01-01.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

plugins:
  - search